version: "3.1"

services:
  mongo:
    build:
      context: ./mongodb_rs
      dockerfile: Dockerfile
      args:
        - MONGO_VERSION=7.0 # Defina aqui a versão do MongoDB que deseja usar
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: "27017"
      MONGO_COMMAND: mongosh # Defina aqui o valor da variável MONGO_COMMAND
    ports:
      - 27017:27017

networks:
  server-network:
    driver: bridge
